spring.application.name=job-quest-backend
server.port=8080

# Local MongoDB
spring.data.mongodb.database=jobquestdb
spring.data.mongodb.uri=mongodb://localhost:27017/jobquestdb

# JWT Keys (example)
jwt.secret=MySecretKey123456
jwt.expiration=86400000
